### ISSUE TITLE
BoLD Dataset Input Shape

### ISSUE THREAD

**Issue by zh3nru** [GiannisPikoulis/FG2021-BoLD#3]
Hi, I'm kinda new to deep learning and stuff and I'm currently working with a project that uses the same dataset as yours. I just wanted to ask how did you guys determine the **input shape** of the dataset because it confuses me a lot. I hope to receive kind help from you. Thankyou in advance!

**Comment by GiannisPikoulis** [comment]
Hello Zhen. 

Thanks for showing interest in my repo. All frames undergo reshaping before being input into each network. The current reshape size is 224x224. The input reshape size directly correlates with GPU memory requirements during gradient backpropagation. The higher the size, the higher the demand in GPU resources. This was the sweet spot in our case. Feel free to experiment with the reshape size yourself. 

Kind regards.
